# Generated by Django 5.0.3 on 2024-03-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
