# Generated by Django 5.0.3 on 2024-03-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='s_id',
            field=models.IntegerField(default=False),
        ),
    ]
