# Generated by Django 5.0.3 on 2024-03-29 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0002_survey_s_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='q_id',
        ),
        migrations.RemoveField(
            model_name='response',
            name='r_id',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='s_id',
        ),
    ]
