# Generated by Django 5.0.3 on 2024-04-01 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0002_question_types_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='text',
            new_name='heading',
        ),
    ]
